Massive work: pipeline now works up to aws eb failing to fetch docker creds

diff --git a/bin/eb_deploy b/bin/eb_deploy
--- a/bin/eb_deploy
+++ b/bin/eb_deploy
@@ -4,13 +4,13 @@ set -e
 
 ARGS=$@
 
-EB_PROFILE=klue-publish
+EB_PROFILE=$(klue_config --aws-user)
 EB_TIMEOUT=15
-EB_INSTANCE_TYPE=t2.micro
-EB_PLATFORM=docker-1.9.1
-EB_S3_BUCKET=elasticbeanstalk-eu-west-1-709131356479
-ARN_CERT_WILDCARD=arn:aws:acm:eu-west-1:709131356479:certificate/212a61bb-99af-475d-a102-021a735f92f2
-ARN_CERT_MARKET=arn:aws:acm:eu-west-1:709131356479:certificate/01a03cda-ef99-462d-9a39-41345bc051b1
+EB_INSTANCE_TYPE=$(klue_config --aws-instance-type)
+EB_PLATFORM=docker-17.03.1-ce
+AWS_KEYNAME=$(klue_config --aws-keypair)
+ARN_CERT=$(klue_config --aws-cert-arn)
+DOCKER_BUCKET=$(klue_config --docker-bucket)
 
 DEPLOY_ONLY=0
 VERSION=
@@ -67,20 +67,16 @@ if [ "$PWD" != "$ROOTDIR" ]; then
     exit 1
 fi
 
-if [ ! -e "env.secrets" ]; then
-    echo "ERROR: not env.lst in current dir"
-    exit 1
-fi
-
-DOCKERRUN_TEMPLATE=$ROOTDIR/../backend-skeleton/Dockerrun.aws.json.template
+DOCKERRUN_TEMPLATE=$(get_docker_template_path --run)
 if [ ! -e "$DOCKERRUN_TEMPLATE" ]; then
     echo "ERROR: cannot find $DOCKERRUN_TEMPLATE"
     exit 1
 fi
 
-PROJECT_NAME=$(print_project_name)
-REPONAME=$(print_docker_repo)
-DOCKER_REPO=$REPONAME/$PROJECT_NAME
+PROJECT_NAME=$(klue_config --name)
+DOCKER_ROOT_REPO=$(klue_config --docker-repo)
+
+DOCKER_REPO=$DOCKER_ROOT_REPO/$PROJECT_NAME
 
 TMPDIR=`mktemp -d /tmp/$PROJECT_NAME.XXXXXX` || exit 1
 mkdir -p $TMPDIR
@@ -94,17 +90,17 @@ cp -LR * \
 
 cd $TMPDIR
 
-if [ -z "$AUTH0_CLIENT_SECRET_KLUE" ]; then
-    echo "ERROR: AUTH0_CLIENT_SECRET_KLUE is not set"
-    exit 1
-fi
+# if [ -z "$AUTH0_CLIENT_SECRET_KLUE" ]; then
+#     echo "ERROR: AUTH0_CLIENT_SECRET_KLUE is not set"
+#     exit 1
+# fi
 
-tell_slack "WARNING: a new version of service $PROJECT_NAME is being released"
+# tell_slack "WARNING: a new version of service $PROJECT_NAME is being released"
 
 echo "=> Generating .ebextensions/aws-secrets.config"
 mkdir -p .ebextensions
 echo "option_settings:" > .ebextensions/aws-secrets.config
-for VAR in $(cat env.secrets | grep -v '#')
+for VAR in $(klue_config --env-secrets)
 do
     echo "   Adding $VAR"
     VALUE=$(env | grep "^$VAR=" | cut -d '=' -f 2)
@@ -119,9 +115,10 @@ done
 
 echo "=> Generating Dockerrun.aws.json for version $VERSION"
 cat $DOCKERRUN_TEMPLATE \
-    | sed -e "s|FROM whatever/|FROM $REPONAME/|g" \
+    | sed -e "s|FROM whatever/|FROM $DOCKER_ROOT_REPO/|g" \
     | sed -e "s|whatever/foobar|$DOCKER_REPO|g" \
     | sed -e "s|VERSION|$VERSION|" \
+    | sed -e "s|DOCKER_BUCKET|$DOCKER_BUCKET|" \
     > Dockerrun.aws.json
 
 echo "=> Re-add .ebextensions to git"
@@ -158,15 +155,6 @@ if [ $C -ne 0 ]; then
     exit 1
 fi
 
-if [ "$PROJECT_NAME" == 'www' ]; then
-    # Need disk for logs...
-    EB_INSTANCE_TYPE='t2.small'
-fi
-
-if [ "$PROJECT_NAME" == 'market' ]; then
-    EB_INSTANCE_TYPE='t2.small'
-fi
-
 if [ $DEPLOY_ONLY -eq 1 ]; then
 
     #
@@ -182,57 +170,13 @@ if [ $DEPLOY_ONLY -eq 1 ]; then
 
     RC=$?
     if [ "$RC" -ne 0 ]; then
-        tell_slack "Failed to deploy version $VERSION of $PROJECT_NAME to environment $NEW_ENV_NAME - deploy aborted"
+        # tell_slack "Failed to deploy version $VERSION of $PROJECT_NAME to environment $NEW_ENV_NAME - deploy aborted"
         exit 1
     fi
 
     cleanup
     exit 0
 fi
-
-#--------------------------------------------------------------------------------
-#
-# The block below was an attempt at creating an environment that starts at once with the
-# right docker app. Creation works fine, but instances end up in flappy state and are
-# recreated a couple of times by auto-scaling before stabilizing, which makes the tests
-# fail each time.
-#
-
-# APP_NAME=$(eb status | grep 'Application name' | awk '{print $3}')
-# echo "=> This application is named [$APP_NAME]"
-# if [ -z $APP_NAME ]; then
-#     echo "ERROR: Failed to identify application name"
-#     exit 1
-# fi
-
-# # Now we bundle this artifact, upload it to s3 and create an application version for it
-# # It should be done by eb create, but isn't...
-# echo "=> Building deploy artifact:"
-# zip -v ${VERSION}.zip Dockerrun.aws.json .ebextensions/*
-
-# echo "=> Uploading ${VERSION}.zip to S3"
-# aws s3 cp ${VERSION}.zip s3://${EB_S3_BUCKET}/$APP_NAME/${VERSION}.zip --profile $EB_PROFILE
-
-# echo "=> Create application version $VERSION"
-# aws elasticbeanstalk create-application-version \
-#     --application-name  $APP_NAME \
-#     --version-label $VERSION \
-#     --source-bundle S3Bucket=$EB_S3_BUCKET,S3Key=$APP_NAME/${VERSION}.zip \
-#     --profile $EB_PROFILE \
-#     --process
-
-# # Create new environment
-# echo "=> Creating new environment $NEW_ENV_NAME"
-# eb create \
-#     --profile $EB_PROFILE \
-#     --timeout $EB_TIMEOUT \
-#     --instance_type $EB_INSTANCE_TYPE \
-#     --platform $EB_PLATFORM \
-#     --keyname aws-eb \
-#     --version $VERSION \
-#     $NEW_ENV_NAME
-#
-#--------------------------------------------------------------------------------
 
 # Create new environment
 echo ""
@@ -242,13 +186,13 @@ eb create \
     --timeout $EB_TIMEOUT \
     --instance_type $EB_INSTANCE_TYPE \
     --platform $EB_PLATFORM \
-    --keyname aws-eb \
+    --keyname $AWS_KEYNAME \
     --sample \
     $NEW_ENV_NAME
 
 RC=$?
 if [ "$RC" -ne 0 ]; then
-    tell_slack "Failed to create environment $NEW_ENV_NAME - deploy aborted"
+    # tell_slack "Failed to create environment $NEW_ENV_NAME - deploy aborted"
     exit 1
 fi
 
@@ -263,98 +207,21 @@ eb deploy \
 
 RC=$?
 if [ "$RC" -ne 0 ]; then
-    tell_slack "Failed to deploy version $VERSION of $PROJECT_NAME to environment $NEW_ENV_NAME - deploy aborted"
+    # tell_slack "Failed to deploy version $VERSION of $PROJECT_NAME to environment $NEW_ENV_NAME - deploy aborted"
     exit 1
 fi
 
 TEST_PORT=80
 
-# Enable https or not?
-export ARN_CERT=
-
-if [ "$PROJECT_NAME" == 'klue-api' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'xpui' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'expert' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'cert' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'search' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'cbot' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'www' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'seller' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'item' ]; then
-    ARN_CERT=$ARN_CERT_WILDCARD
-elif [ "$PROJECT_NAME" == 'market' ]; then
-    ARN_CERT=$ARN_CERT_MARKET
-fi
-
 if [ ! -z "$ARN_CERT" ]; then
 
     TEST_PORT=443
 
-    if [ "$PROJECT_NAME" == 'cert' -o "$PROJECT_NAME" == 'search' -o "$PROJECT_NAME" == 'www' -o "$PROJECT_NAME" == 'cbot' -o "$PROJECT_NAME" == 'seller' -o "$PROJECT_NAME" == 'item' -o "$PROJECT_NAME" == 'market' -o "$PROJECT_NAME" == 'expert' -o "$PROJECT_NAME" == 'login' ]; then
-        # This is an hybrid service, listening on both 80 and 443
+    echo ""
+    echo "=> Reconfiguring environment to use HTTPS only"
 
-        echo ""
-        echo "=> Reconfiguring environment to use both HTTP and HTTPS"
-
-        cat <<EOF > elb-https.json
-[
-    {
-        "Namespace": "aws:elb:listener:443",
-        "OptionName": "SSLCertificateId",
-        "Value": "$ARN_CERT"
-    },
-    {
-        "Namespace": "aws:elb:listener:443",
-        "OptionName": "ListenerProtocol",
-        "Value": "HTTPS"
-    },
-    {
-        "Namespace": "aws:elb:listener:443",
-        "OptionName": "InstancePort",
-        "Value": "80"
-    },
-    {
-        "Namespace": "aws:elb:listener:443",
-        "OptionName": "InstanceProtocol",
-        "Value": "HTTP"
-    },
-    {
-        "Namespace": "aws:elb:listener:80",
-        "OptionName": "ListenerEnabled",
-        "Value": "true"
-    },
-    {
-        "Namespace": "aws:elb:listener:80",
-        "OptionName": "ListenerProtocol",
-        "Value": "HTTP"
-    },
-    {
-        "Namespace": "aws:elb:listener:80",
-        "OptionName": "InstanceProtocol",
-        "Value": "HTTP"
-    },
-    {
-        "Namespace": "aws:elb:listener:443",
-        "OptionName": "InstancePort",
-        "Value": "80"
-    }
-]
-EOF
-
-    else
-        echo ""
-        echo "=> Reconfiguring environment to use HTTPS only"
-
-        # These services listen on 443 only
-        cat <<EOF > elb-https.json
+    # These services listen on 443 only
+    cat <<EOF > elb-https.json
 [
     {
         "Namespace": "aws:elb:listener:443",
@@ -383,7 +250,6 @@ EOF
     }
 ]
 EOF
-    fi
 
     aws elasticbeanstalk update-environment \
         --environment-name $NEW_ENV_NAME \
